[package]
name = "clinkz-wot-property-read-binding-fixture"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clinkz-wot-core = { path = "../../../core", default-features = false }
clinkz-wot-foundation = { path = "../../../foundation", default-features = false }

[features]
default = ["std"]
async = ["clinkz-wot-core/async", "clinkz-wot-foundation/async"]
std = [
    "clinkz-wot-core/std",
    "clinkz-wot-foundation/std",
]
